isp_enable:
  description: "Use ISP GeoIP2 database"
  type: "boolean"
  required: true
  default: false
isp_db:
  description: "Path to ISP GeoIP2 database"
  type: "string"
  required: true
  default: ~
city_enable:
  description: "Use City GeoIP2 database"
  type: "boolean"
  required: true
  default: false
city_db:
  description: "Path to City GeoIP2 database"
  type: "string"
  required: true
  default: ~
