isp_db:
  description: "Path to ISP GeoIP2 database"
  type: "string"
  required: true
  default: "/opt/geoip2/GeoIP2-ISP.mmdb"
city_db:
  description: "Path to City GeoIP2 database"
  type: "string"
  required: true
  default: "/opt/geoip2/GeoLite2-City.mmdb"
